emcc wasm.c \
    -o ../src/assets/timelock.wasm \
    -Oz \
    -g2 \
    --no-entry \
    -fno-exceptions \
    -flto \
    -s INITIAL_MEMORY=32MB \
    -s ERROR_ON_UNDEFINED_SYMBOLS=0 \
    -s SUPPORT_ERRNO=0 \
    -s SUPPORT_LONGJMP=0